# Tema One Dark - Darkened
palette = "one_dark_darkened"

[palettes.one_dark_darkened]
bg = "#17191d"
fg = "#c8ccd4"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
orange = "#dfc184"
purple = "#c678dd"
red = "#e06c75"
yellow = "#e5c07b"

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$character
"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
style = "blue"
truncation_length = 3

[git_branch]
style = "purple"
symbol = " "

[git_status]
style = "yellow"

[nodejs]
style = "green"
symbol = " "