##################################################
# GLOBAL SETTINGS
##################################################
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g default-terminal "screen-256color"
set -as terminal-overrides ",xterm-256color:RGB"

setw -g mode-keys vi
set -g mouse on

set -g renumber-windows on
set -g set-clipboard on
set -sg escape-time 0
set -g focus-events on

set -g status on
set -g status-position top
set -g status-interval 3

##################################################
# PLUGINS
##################################################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'fabioluciano/tmux-powerkit'

##################################################
# RESURRECT
##################################################
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

# Fix keybinding collision with tmux-powerkit
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

##################################################
# POWERKIT
##################################################
set -g @powerkit_plugins 'session,windows,git,cpu,battery,datetime'

##################################################
# KEYBINDINGS
##################################################
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Splits
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind z resize-pane -Z

# Vim navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Windows
bind c new-window -c "#{pane_current_path}"
bind , command-prompt -p "Rename window:" "rename-window %%"
bind w choose-window

# Copy mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

##################################################
# INITIALIZE TPM
##################################################
run "~/.tmux/plugins/tpm/tpm"
