-- One Dark Darkened colorscheme for Neovim.
-- Mirrors the Zed extension "One Dark - Darkened" by Pavle Sokic so the
-- editor palette matches Ghostty and the rest of the desktop.
-- Source of truth: ~/Library/Application Support/Zed/extensions/installed/one-dark-darkened/themes/one-dark-darkened.json
return {
  {
    "olimorris/onedarkpro.nvim",
    priority = 1000,
    config = function()
      require("onedarkpro").setup({
        options = {
          transparency = false,
          cursorline = true,
          bold = true,
          italic = true,
          underline = true,
          undercurl = true,
          term_colors = true,
        },
        -- Override the built-in `onedark` palette with the exact Zed hexes.
        -- onedarkpro regenerates all highlights from these named colors.
        colors = {
          onedark = {
            bg = "#17191d",
            fg = "#bfc4cd",
            bg_alt = "#1e2228",
            fg_alt = "#b5b8bf",
            blue = "#73ade9",
            cyan = "#6eb4bf",
            green = "#a1c181",
            grey = "#5d636f",
            dark_grey = "#696b77",
            light_grey = "#acb2be",
            medium_grey = "#838994",
            orange = "#bf956a",
            purple = "#b477cf",
            red = "#e78284",
            yellow = "#dfc184",
            dark_cyan = "#56b6c2",
            dark_red = "#d07277",
            bright_yellow = "#dec184",
            highlight = "#2a2f38",
            selection = "#74ade8",
            comment = "#5d636f",
            line_nr = "#5d636f",
            current_line_nr = "#e5e7ea",
            none = "NONE",
          },
        },
        -- Fine-grained overrides where the auto-generated mapping diverges
        -- from Zed's syntax tokens.
        highlights = {
          onedark = {
            -- Editor chrome
            Normal = { bg = "${bg}", fg = "${fg}" },
            NormalNC = { bg = "${bg}", fg = "${fg}" },
            CursorLine = { bg = "${highlight}" },
            CursorLineNr = { fg = "${current_line_nr}", bg = "${highlight}" },
            LineNr = { fg = "${line_nr}" },
            SignColumn = { bg = "${bg}" },
            VertSplit = { fg = "#2f323b", bg = "${bg}" },
            WinSeparator = { fg = "#2f323b", bg = "${bg}" },
            StatusLine = { bg = "#1e2128", fg = "${fg}" },
            StatusLineNC = { bg = "#202329", fg = "${fg_alt}" },
            TabLine = { bg = "#202329", fg = "${fg_alt}" },
            TabLineFill = { bg = "#1a1e23" },
            TabLineSel = { bg = "${bg}", fg = "${fg}" },
            Pmenu = { bg = "#1d2127", fg = "${fg}" },
            PmenuSel = { bg = "#454a56", fg = "${fg}" },
            PmenuSbar = { bg = "#1d2127" },
            PmenuThumb = { bg = "#454a56" },
            Visual = { bg = "#74ade83d" },
            Search = { bg = "#74ade81a", fg = "NONE" },
            IncSearch = { bg = "#74ade81a", fg = "NONE" },
            MatchParen = { bg = "#74ade81a" },
            NonText = { fg = "${dark_grey}" },
            Whitespace = { fg = "${dark_grey}" },
            Folded = { bg = "#1d2127", fg = "${fg_alt}" },
            CursorColumn = { bg = "${highlight}" },
            ColorColumn = { bg = "#1d2127" },
            Conceal = { fg = "${medium_grey}" },
            Directory = { fg = "${blue}" },
            EndOfBuffer = { fg = "${bg}" },
            ErrorMsg = { fg = "${dark_red}" },
            ModeMsg = { fg = "${fg_alt}" },
            MoreMsg = { fg = "${blue}" },
            Question = { fg = "${blue}" },
            SpecialKey = { fg = "${dark_grey}" },
            Title = { fg = "${dark_red}" },
            WarningMsg = { fg = "${bright_yellow}" },
            WildMenu = { bg = "#1d2127", fg = "${fg}" },

            -- Syntax: matched to Zed syntax.* tokens
            Comment = { fg = "${comment}", style = { "italic" } },
            Constant = { fg = "${yellow}" },
            String = { fg = "${green}" },
            Character = { fg = "${green}" },
            Number = { fg = "${orange}" },
            Boolean = { fg = "${orange}" },
            Float = { fg = "${orange}" },
            Identifier = { fg = "${fg}" },
            Function = { fg = "${blue}" },
            Statement = { fg = "${purple}" },
            Conditional = { fg = "${purple}" },
            Repeat = { fg = "${purple}" },
            Label = { fg = "${blue}" },
            Operator = { fg = "${cyan}" },
            Keyword = { fg = "${purple}" },
            Exception = { fg = "${purple}" },
            PreProc = { fg = "#dce0e5" },
            Include = { fg = "${purple}" },
            Define = { fg = "${purple}" },
            Macro = { fg = "${purple}" },
            Type = { fg = "${cyan}" },
            StorageClass = { fg = "${purple}" },
            Structure = { fg = "${cyan}" },
            Typedef = { fg = "${cyan}" },
            Special = { fg = "${orange}" },
            SpecialChar = { fg = "${orange}" },
            Tag = { fg = "${blue}" },
            Delimiter = { fg = "#b2b9c6" },
            SpecialComment = { fg = "#878e98" },
            Debug = { fg = "${orange}" },
            Underlined = { fg = "${blue}", style = { "underline" } },
            Ignore = { fg = "${dark_grey}" },
            Error = { fg = "${dark_red}", style = { "bold" } },
            Todo = { fg = "${bright_yellow}", style = { "bold" } },

            -- Treesitter: align with Zed syntax.* where names differ
            ["@keyword"] = { fg = "${purple}" },
            ["@function"] = { fg = "${blue}" },
            ["@function.builtin"] = { fg = "${blue}" },
            ["@function.call"] = { fg = "${blue}" },
            ["@method"] = { fg = "${blue}" },
            ["@constructor"] = { fg = "${blue}" },
            ["@type"] = { fg = "${cyan}" },
            ["@type.builtin"] = { fg = "${cyan}" },
            ["@variable"] = { fg = "${fg}" },
            ["@variable.builtin"] = { fg = "${orange}" },
            ["@constant"] = { fg = "${yellow}" },
            ["@constant.builtin"] = { fg = "${orange}" },
            ["@string"] = { fg = "${green}" },
            ["@string.special"] = { fg = "${orange}" },
            ["@string.escape"] = { fg = "#878e98" },
            ["@number"] = { fg = "${orange}" },
            ["@boolean"] = { fg = "${orange}" },
            ["@operator"] = { fg = "${cyan}" },
            ["@punctuation"] = { fg = "${light_grey}" },
            ["@punctuation.bracket"] = { fg = "#b2b9c6" },
            ["@punctuation.delimiter"] = { fg = "#b2b9c6" },
            ["@comment"] = { fg = "${comment}", style = { "italic" } },
            ["@comment.documentation"] = { fg = "#878e98" },
            ["@property"] = { fg = "${red}" },
            ["@tag"] = { fg = "${blue}" },
            ["@tag.attribute"] = { fg = "${blue}" },
            ["@tag.delimiter"] = { fg = "#b2b9c6" },
            ["@attribute"] = { fg = "${blue}" },
            ["@namespace"] = { fg = "${fg}" },
            ["@module"] = { fg = "${fg}" },
            ["@label"] = { fg = "${blue}" },
            ["@text.literal"] = { fg = "${green}" },
            ["@text.reference"] = { fg = "${blue}" },
            ["@text.uri"] = { fg = "${cyan}" },
            ["@markup.heading"] = { fg = "${dark_red}" },
            ["@markup.list"] = { fg = "${dark_red}" },
            ["@markup.raw"] = { fg = "${green}" },
            ["@markup.link"] = { fg = "${blue}" },
            ["@diff.plus"] = { fg = "${green}" },
            ["@diff.minus"] = { fg = "${dark_red}" },
            ["@diff.delta"] = { fg = "${bright_yellow}" },

            -- LSP / diagnostics
            DiagnosticError = { fg = "${dark_red}" },
            DiagnosticWarn = { fg = "${bright_yellow}" },
            DiagnosticInfo = { fg = "${blue}" },
            DiagnosticHint = { fg = "#787c85" },
            DiagnosticUnderlineError = { undercurl = true, sp = "${dark_red}" },
            DiagnosticUnderlineWarn = { undercurl = true, sp = "${bright_yellow}" },
            DiagnosticUnderlineInfo = { undercurl = true, sp = "${blue}" },
            DiagnosticUnderlineHint = { undercurl = true, sp = "#787c85" },

            -- Git signs
            GitSignsAdd = { fg = "${green}" },
            GitSignsChange = { fg = "${bright_yellow}" },
            GitSignsDelete = { fg = "${dark_red}" },
            GitSignsAddLn = { bg = "#a1c1811a", fg = "${green}" },
            GitSignsChangeLn = { bg = "#dec1841a", fg = "${bright_yellow}" },
            GitSignsDeleteLn = { bg = "#d072771a", fg = "${dark_red}" },

            -- LSP semantic tokens
            ["@lsp.type.variable"] = { fg = "${fg}" },
            ["@lsp.type.property"] = { fg = "${red}" },
            ["@lsp.type.function"] = { fg = "${blue}" },
            ["@lsp.type.method"] = { fg = "${blue}" },
            ["@lsp.type.namespace"] = { fg = "${fg}" },
            ["@lsp.type.class"] = { fg = "${cyan}" },
            ["@lsp.type.type"] = { fg = "${cyan}" },
            ["@lsp.type.parameter"] = { fg = "${orange}" },
            ["@lsp.type.enumMember"] = { fg = "${dark_red}" },
            ["@lsp.type.macro"] = { fg = "${purple}" },
            ["@lsp.type.decorator"] = { fg = "${blue}" },
          },
        },
      })
      vim.cmd("colorscheme onedark")
    end,
  },
  -- Tell LazyVim to use our colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "onedark",
    },
  },
}
